# Generated by Django 4.2.7 on 2023-12-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursestudent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdescription', models.CharField(max_length=500)),
            ],
        ),
    ]
