# Generated by Django 4.2 on 2023-10-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
                ('branchname', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
