# Generated by Django 4.2 on 2023-10-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsapp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
